steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Build the application for production
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args: [' -c', 'npm run build:prod']
  # Deploy to Firebase Hosting
  # Deploy to Firebase Hosting
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args: [' -c', 'npm install -g firebase-tools && firebase deploy --project=sazonapp-322e1 --only hosting']

options:
  logging: CLOUD_LOGGING_ONLY

