steps:
  # Paso 1: Instalar dependencias de Node.js y construir la aplicación Angular
  - name: 'node:20-slim' # Usar una versión LTS compatible de Node.js
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install && ./node_modules/.bin/ng build sazon_del_bueno_frontend --configuration=production --aot'

  # Paso 2: Desplegar en Firebase Hosting
  - name: 'gcr.io/cloud-builders/firebase' # Usar la imagen dedicada de Firebase
    args: ['deploy', '--project=sazonapp', '--only', 'hosting']

options:
  logging: CLOUD_LOGGING_ONLY