steps:
  # Step 1: Install Node.js dependencies
  # Using the official Cloud Build npm builder
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the Angular application
  # Using the official Cloud Build npm builder
  - name: 'gcr.io/cloud-builders/npm'
    args: ['./node_modules/.bin/ng', 'build', '--configuration', 'production', '--aot']

  # Step 3: Deploy to Firebase Hosting
  # !!! FIX: Use the dedicated Firebase builder image !!!
  - name: 'gcr.io/cloud-builders/firebase' # Use this image, it includes Firebase CLI
    args: ['deploy', '--project=sazonapp', '--only', 'hosting']

options:
  logging: CLOUD_LOGGING_ONLY
