steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Build the application for production
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:prod']
  # Deploy to Firebase Hosting
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', 'firebase-tools']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['deploy', '--project=sazonapp', '--only', 'hosting']
    entrypoint: 'firebase'

options:
  logging: CLOUD_LOGGING_ONLY

