steps:
  # Paso 1: Limpiar el directorio de salida y construir la aplicación Angular
  - name: 'node:20-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'rm -rf dist && npm install && ./node_modules/.bin/ng build sazon_del_bueno_frontend --configuration=production --aot'

  # Paso 2: Desplegar en Firebase Hosting
  - name: 'node:20-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install -g firebase-tools && firebase deploy --project=sazonapp-322e1 --only hosting --force'

options:
  logging: CLOUD_LOGGING_ONLY